use movies;

insert into Movie (movie_id, movie_name, distribution_fee) values (1, 'Graceland', 1295.64);
insert into Movie (movie_id, movie_name, distribution_fee) values (2, 'Born to Be Bad', 492594.0);
insert into Movie (movie_id, movie_name, distribution_fee) values (3, 'Wyatt Earp', 885262.89);
insert into Movie (movie_id, movie_name, distribution_fee) values (4, 'Clean and Sober', 547145.83);
insert into Movie (movie_id, movie_name, distribution_fee) values (5, 'Without a Paddle', 77728.44);
insert into Movie (movie_id, movie_name, distribution_fee) values (6, 'Trois', 247095.97);
insert into Movie (movie_id, movie_name, distribution_fee) values (7, 'Down to Earth', 857218.41);
insert into Movie (movie_id, movie_name, distribution_fee) values (8, 'Knights of the Round Table', 269518.14);
insert into Movie (movie_id, movie_name, distribution_fee) values (9, 'Bird', 468330.91);
insert into Movie (movie_id, movie_name, distribution_fee) values (10, 'In My Sleep', 508996.44);
insert into Movie (movie_id, movie_name, distribution_fee) values (11, 'Monsieur Lazhar', 346770.06);
insert into Movie (movie_id, movie_name, distribution_fee) values (12, 'Sylvia and the Ghost', 592215.2);
insert into Movie (movie_id, movie_name, distribution_fee) values (13, 'Deep Water', 749341.17);
insert into Movie (movie_id, movie_name, distribution_fee) values (14, 'Undercurrent', 505720.32);
insert into Movie (movie_id, movie_name, distribution_fee) values (15, 'Lucy', 186546.72);
insert into Movie (movie_id, movie_name, distribution_fee) values (16, 'Wonder Bar', 742406.16);
insert into Movie (movie_id, movie_name, distribution_fee) values (17, 'Catch That Kid', 482224.9);
insert into Movie (movie_id, movie_name, distribution_fee) values (18, '9to5: Days in Porn (a.k.a. 9 to 5: Days in Porn)', 713809.17);
insert into Movie (movie_id, movie_name, distribution_fee) values (19, 'Rocks in my Pockets', 394522.9);
insert into Movie (movie_id, movie_name, distribution_fee) values (20, 'Suomisen Olli yllättää', 863609.74);
insert into Movie (movie_id, movie_name, distribution_fee) values (21, 'To Sleep with Anger', 656912.88);
insert into Movie (movie_id, movie_name, distribution_fee) values (22, 'Confessions of a Dangerous Mind', 582346.09);
insert into Movie (movie_id, movie_name, distribution_fee) values (23, 'This Land Is Mine', 759026.7);
insert into Movie (movie_id, movie_name, distribution_fee) values (24, '.45', 967100.08);
insert into Movie (movie_id, movie_name, distribution_fee) values (25, 'Trailer Park Boys', 236061.44);
insert into Movie (movie_id, movie_name, distribution_fee) values (26, 'Set Me Free (Emporte-moi)', 463416.0);
insert into Movie (movie_id, movie_name, distribution_fee) values (27, 'Gathering, The', 645179.53);
insert into Movie (movie_id, movie_name, distribution_fee) values (28, 'Everest', 354475.06);
insert into Movie (movie_id, movie_name, distribution_fee) values (29, 'Ice Pirates, The', 234144.59);
insert into Movie (movie_id, movie_name, distribution_fee) values (30, 'Last Wedding, The (Kivenpyörittäjän kylä)', 617631.28);
insert into Movie (movie_id, movie_name, distribution_fee) values (31, 'Tooth Fairy 2', 709444.65);
insert into Movie (movie_id, movie_name, distribution_fee) values (32, 'C.R.A.Z.Y.', 77074.55);
insert into Movie (movie_id, movie_name, distribution_fee) values (33, 'Bean', 297784.25);
insert into Movie (movie_id, movie_name, distribution_fee) values (34, 'Question of Silence, A (De stilte rond Christine ', 388561.5);
insert into Movie (movie_id, movie_name, distribution_fee) values (35, 'Yossi & Jagger', 1861.65);
insert into Movie (movie_id, movie_name, distribution_fee) values (36, 'Good Year, A', 189749.75);
insert into Movie (movie_id, movie_name, distribution_fee) values (37, 'Jazz Singer, The', 298189.69);
insert into Movie (movie_id, movie_name, distribution_fee) values (38, 'Blue City', 117004.94);
insert into Movie (movie_id, movie_name, distribution_fee) values (39, 'Dragon Age: Blood mage no seisen (a.k.a. Dragon A', 867488.62);
insert into Movie (movie_id, movie_name, distribution_fee) values (40, 'The Town that Dreaded Sundown', 565503.1);
insert into Movie (movie_id, movie_name, distribution_fee) values (41, 'Chernobyl Diaries', 365700.39);
insert into Movie (movie_id, movie_name, distribution_fee) values (42, 'Fate of a Man (Sudba cheloveka)', 329247.49);
insert into Movie (movie_id, movie_name, distribution_fee) values (43, 'Aftermath', 167223.74);
insert into Movie (movie_id, movie_name, distribution_fee) values (44, 'Belly of an Architect, The', 873897.71);
insert into Movie (movie_id, movie_name, distribution_fee) values (45, 'Ask Me Anything', 42284.98);
insert into Movie (movie_id, movie_name, distribution_fee) values (46, 'Perfect Couple, A', 947343.18);
insert into Movie (movie_id, movie_name, distribution_fee) values (47, 'Double Take', 581522.0);
insert into Movie (movie_id, movie_name, distribution_fee) values (48, 'Reclaim', 243483.73);
insert into Movie (movie_id, movie_name, distribution_fee) values (49, 'Island, The', 227722.67);
insert into Movie (movie_id, movie_name, distribution_fee) values (50, 'U-571', 150933.22);
insert into Movie (movie_id, movie_name, distribution_fee) values (51, 'Killer at Large', 253634.86);
insert into Movie (movie_id, movie_name, distribution_fee) values (52, 'Locke', 912804.28);
insert into Movie (movie_id, movie_name, distribution_fee) values (53, 'Bikini Summer III - South Beach Heat', 637561.0);
insert into Movie (movie_id, movie_name, distribution_fee) values (54, 'All About the Benjamins', 297960.0);
insert into Movie (movie_id, movie_name, distribution_fee) values (55, 'Bedlam', 88257.26);
insert into Movie (movie_id, movie_name, distribution_fee) values (56, 'Three Brave Men', 517593.05);
insert into Movie (movie_id, movie_name, distribution_fee) values (57, 'The War', 350058.86);
insert into Movie (movie_id, movie_name, distribution_fee) values (58, 'Daddy Long Legs', 985697.88);
insert into Movie (movie_id, movie_name, distribution_fee) values (59, 'They All Laughed', 758685.49);
insert into Movie (movie_id, movie_name, distribution_fee) values (60, 'Venus', 74883.17);
insert into Movie (movie_id, movie_name, distribution_fee) values (61, 'Return, The (Vozvrashcheniye)', 921974.42);
insert into Movie (movie_id, movie_name, distribution_fee) values (62, 'Casanova', 139621.27);
insert into Movie (movie_id, movie_name, distribution_fee) values (63, 'Quiet as a Mouse (Muxmäuschenstill)', 563336.33);
insert into Movie (movie_id, movie_name, distribution_fee) values (64, 'World According to Sesame Street, The', 403281.06);
insert into Movie (movie_id, movie_name, distribution_fee) values (65, 'Side Out', 284453.19);
insert into Movie (movie_id, movie_name, distribution_fee) values (66, 'Human Traffic', 827789.1);
insert into Movie (movie_id, movie_name, distribution_fee) values (67, 'Tiger''s Tail, The', 634896.93);
insert into Movie (movie_id, movie_name, distribution_fee) values (68, 'Firehouse Dog', 813629.85);
insert into Movie (movie_id, movie_name, distribution_fee) values (69, 'Misérables, Les', 925339.95);
insert into Movie (movie_id, movie_name, distribution_fee) values (70, 'Le créateur ', 958133.09);
